#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (division, print_function, absolute_import,
                        unicode_literals)
import os
import sys
from ConfigParser import ConfigParser

try:
    import kois
    kois = kois
except ImportError:
    sys.path.insert(0, os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))
    import kois
    kois = kois

from kois import database


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Set up the KOI database")
    parser.add_argument("config", help="Path to the configuration file")
    args = parser.parse_args()

    # Parse the configuration file.
    config = ConfigParser()
    config.read(args.config)

    dbpath = config.get("local", "database")
    print("Setting up the schema in '{0}'".format(dbpath))
    database.init_db(dbpath)
    print("Loading the KOI list")
    database.load_kois(dbpath)
